# 10. pandas II

## 10.1. 열끼리 계산

In [1]:
# 파이썬 연산 기호로 열끼리 간단한 계산을 할 수 있다.
# 예제로 성인 인적사항 자료를 사용하자.
import pandas as pd
df = pd.read_csv('adult.csv', header=None)
titles = {0: '나이', 1: '고용형태', 2: '가중치',
            3: '최종학위', 4:'교육햇수', 5: '결혼유무',
            6: '직업명', 7:'가족내역할', 8:'인종',
            9: '성별', 10: '자본이득', 11: '자본손실',
            12: '노동시간', 13:'고향', 14:'수입'
           }
df.rename(columns=titles, inplace=True)
df.head()

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### 10.1.1. 곱셈
열에 상수를 연산할 수 있다. 판다스는 각 행에 해당 연산을 적용시켜 돌려준다.

한 달 동안 근무 시간을 보기 위해 주당 근무 시간에 4 를 곱해보자.

In [2]:
hours_per_month = df['노동시간'] * 4

In [3]:
hours_per_month.head()
# 결과를 확인해보니, 월별 근무시간이 계산되었다.

0    160
1     52
2    160
3    160
4    160
Name: 노동시간, dtype: int64

### 10.1.2. 나눗셈
반대로, 일당 근무 시간을 알아보기 위해 노동시간을 5 로 나누자.

In [4]:
hours_per_day = df['노동시간'] / 5

In [6]:
hours_per_day.head()
# 확인결과 일당 노동시간이 구해졌다.
# 두번째 사람을 제외하고 첫 다섯 사람은 하루 8시간 근무한다.

0    8.0
1    2.6
2    8.0
3    8.0
4    8.0
Name: 노동시간, dtype: float64

### 10.1.3. 빼기

In [7]:
# 서로 다른 열을 사용해 계산할 수 있다.
# - 로 자본이익에서 자본손실을 빼 true_gain에 저장하자.
true_gain = df['자본이득'] - df['자본손실']

In [8]:
true_gain.head() # 확인해보니 차액이 구해졌다.

0    2174
1       0
2       0
3       0
4       0
dtype: int64

In [9]:
# 열과 열을 계산하며 상수를 포함해서 연산을 할 수 있다.
# 나이에서 교육받은 햇수와 유아기 8년을 빼, 근무 햇수를 구해보자.
not_educated = df['나이'] - df['교육햇수'] - 8

In [10]:
not_educated.head()

0    18
1    29
2    21
3    38
4     7
dtype: int64

## 10.2. grouping
### 10.2.1. groupby
이번 강의에서는 .groupby를 이용해 각 열의 값을 기준으로 데이터를 보는 방법을 살펴보자.

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('adult.csv', skipinitialspace=True, header=None)  # 값 앞에 공백이 포함되어 있기 때문에 제거해야 함

In [13]:
titles = {0: '나이', 1: '고용형태', 2: '가중치',
            3: '최종학위', 4:'교육년수', 5: '결혼유무',
            6: '직업명', 7:'가족내역할', 8:'인종',
            9: '성별', 10: '자본이득', 11: '자본손실',
            12: '근무시간', 13:'고향', 14:'수입'
           }

df.rename(columns=titles, inplace=True)

In [14]:
df.head()

,나이,고용형태,가중치,최종학위,교육년수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,근무시간,고향,수입
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

#### 가족내 역할이 '남편' 인 자료 색인

In [15]:
df['가족내역할'].unique()

array(['Not-in-family', 'Husband', 'Wife', 'Own-child', 'Unmarried',
       'Other-relative'], dtype=object)

In [16]:
# groupby 를 적용시켜보자.
df.groupby('가족내역할')

In [17]:
grouped = df.groupby('가족내역할') # 이를 grouped에 저장하자.

In [18]:
grouped.groups

{'Husband': Int64Index([    1,     3,     7,     9,    10,    11,    14,    15,    18,
                20,
             ...
             32532, 32533, 32539, 32542, 32547, 32550, 32551, 32552, 32554,
             32557],
            dtype='int64', length=13193),
 'Not-in-family': Int64Index([    0,     2,     6,     8,    13,    28,    30,    44,    49,
                53,
             ...
             32523, 32531, 32536, 32537, 32541, 32544, 32546, 32548, 32553,
             32555],
            dtype='int64', length=8305),
 'Other-relative': Int64Index([   74,   110,   144,   152,   159,   195,   198,   233,   317,
               335,
             ...
             32306, 32322, 32359, 32387, 32398, 32401, 32477, 32499, 32524,
             32549],
            dtype='int64', length=981),
 'Own-child': Int64Index([   12,    16,    26,    31,    32,    33,    36,    51,    69,
                70,
             ...
             32486, 32488, 32492, 32496, 32511, 32512, 32527, 32535, 32540,
             32559],
            dtype='int64', length=5068),
 'Unmarried': Int64Index([   17,    19,    21,    24,    35,    43,    47,    91,    92,
                98,
             ...
             32493, 32500, 32516, 32520, 32525, 32529, 32534, 32538, 32543,
             32558],
            dtype='int64', length=3446),
 'Wife': Int64Index([    4,     5,    37,    50,    52,    67,    82,    93,   113,
               125,
             ...
             32425, 32428, 32479, 32485, 32513, 32528, 32530, 32545, 32556,
             32560],
            dtype='int64', length=1568)}

In [19]:
grouped.groups['Husband'] # 이중에서 Husband 를 색인해보자.
# 1, 3, 7, 인덱스를 가진 행들이 '가족내역할' 중에서 Husband 의 값을 가진다는 것을 알 수 있다.

Int64Index([    1,     3,     7,     9,    10,    11,    14,    15,    18,
               20,
            ...
            32532, 32533, 32539, 32542, 32547, 32550, 32551, 32552, 32554,
            32557],
           dtype='int64', length=13193)

In [20]:
# Husband 의 값을 가지는 값이 몇개인지 알아보자.
len(df[df['가족내역할'] == 'Husband'])

13193

In [21]:
# 자료가 어떻게 생겼는지 감을 잡기 위해, .first() 로 각 그룹마다 첫 자료를 열람해보자.
grouped.first()

,나이,고용형태,가중치,최종학위,교육년수,결혼유무,직업명,인종,성별,자본이득,자본손실,근무시간,고향,수입
가족내역할,,,,,,,,,,,,,,
Husband,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,White,Male,0,0,13,United-States,<=50K
Not-in-family,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,White,Male,2174,0,40,United-States,<=50K
Other-relative,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,White,Male,0,0,20,United-States,<=50K
Own-child,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,White,Female,0,0,30,United-States,<=50K
Unmarried,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,White,Male,0,0,40,United-States,<=50K
Wife,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Black,Female,0,0,40,Cuba,<=50K

In [22]:
grouped.groups.keys() # .keys()로 키 값을 확인해보자.

dict_keys(['Husband', 'Not-in-family', 'Other-relative', 'Own-child', 'Unmarried', 'Wife'])

In [23]:
# 이 값들은, .unique()의 값과 같다.
set(df['가족내역할'].unique()) == set(grouped.groups.keys())
# 즉, '가족내역할'의 값 그룹이 key 로 grouped 에 들어가있다.

True

In [24]:
# 그룹 바이로 그룹별로 평균, 합 등을 구할 수 있다.
# 가족 구성원의 나이 평균을 구해보자.
grouped['나이'].mean()
# 확인 결과, 남편들은 평균 43 세, 아내들은 평균 39 세 입니다.

가족내역할
Husband           43.818616
Not-in-family     38.346057
Other-relative    33.164118
Own-child         24.827940
Unmarried         40.293964
Wife              39.846301
Name: 나이, dtype: float64

In [25]:
grouped['자본이득'].sum() # 그룹별 총 자본이득을 구해보자.
# 확인결과, 남편의 자본이득이 가장 높다.

가족내역할
Husband           23682256
Not-in-family      6173333
Other-relative      274283
Own-child           788862
Unmarried          1568037
Wife               2602553
Name: 자본이득, dtype: int64

In [27]:
grouped['나이'].count()
# .count()로 그룹별 출현 수를 얻을 수 있다. 이때 어느 열을 사용하든, 같은 결과를 얻을 수 있다. 임시로 나이의 count 를 구해보자.
# 이 자료에는 남편인 사람들이 가장 많다.

가족내역할
Husband           13193
Not-in-family      8305
Other-relative      981
Own-child          5068
Unmarried          3446
Wife               1568
Name: 나이, dtype: int64

In [28]:
grouped['나이'].count().sort_values() # count 결과를 정렬해보자.

가족내역할
Other-relative      981
Wife               1568
Unmarried          3446
Own-child          5068
Not-in-family      8305
Husband           13193
Name: 나이, dtype: int64

In [29]:
grouped['나이'].count().sort_values(ascending=False) # 내림차순으로 정렬해보자.

가족내역할
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: 나이, dtype: int64

In [30]:
# .describe()로 자료의 요약을 살펴볼 수 있다.
grouped['나이'].describe()

                  count       mean        std   min   25%   50%   75%   max
가족내역할
Husband         13193.0  43.818616  12.024349  17.0  35.0  43.0  52.0  90.0
Not-in-family    8305.0  38.346057  13.865379  17.0  27.0  35.0  47.0  90.0
Other-relative    981.0  33.164118  14.166235  17.0  22.0  28.0  41.0  90.0
Own-child        5068.0  24.827940   8.115799  17.0  19.0  22.0  27.0  90.0
Unmarried        3446.0  40.293964  11.605904  17.0  32.0  39.0  47.0  90.0
Wife             1568.0  39.846301  11.227700  18.0  31.0  39.0  47.0  90.0

In [31]:
# 하나의 그룹만을 선택하고 싶다면, .get_group()을 사용하면 된다.
grouped.get_group('Not-in-family').head()

,가중치,결혼유무,고용형태,고향,교육년수,근무시간,나이,성별,수입,인종,자본손실,자본이득,직업명,최종학위
0,77516,Never-married,State-gov,United-States,13,40,39,Male,<=50K,White,0,2174,Adm-clerical,Bachelors
2,215646,Divorced,Private,United-States,9,40,38,Male,<=50K,White,0,0,Handlers-cleaners,HS-grad
6,160187,Married-spouse-absent,Private,Jamaica,5,16,49,Female,<=50K,Black,0,0,Other-service,9th
8,45781,Never-married,Private,United-States,14,50,31,Female,>50K,White,0,14084,Prof-specialty,Masters
13,205019,Never-married,Private,United-States,12,50,32,Male,<=50K,Black,0,0,Sales,Assoc-acdm

In [32]:
# 그룹 바이 한 결과를, for문으로 돌릴 수 있다.
for name, group in grouped:  # grouped 는 그룹별로 key 와 value 로 구성되어있는 사전
    print(name)  # key 값
    print(group['근무시간'].sum())  # 주별 근무시간의 합
# 그룹마다 근무시간의 합이 출력된다.

Husband
582077
Not-in-family
337147
Other-relative
36303
Own-child
168609
Unmarried
134749
Wife
57799

### 10.2.2. group by - 열 두 개 이상 사용하기
groupby 를 사용해 그룹내에 그룹을 또 나눌 수 있다.

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('adult.csv', skipinitialspace=True, header=None)  # 값 앞에 공백이 포함 되어있기 때문에 제거

In [35]:
titles = {0: '나이', 1: '고용형태', 2: '가중치',
            3: '최종학위', 4:'교육년수', 5: '결혼유무',
            6: '직업명', 7:'가족내역할', 8:'인종',
            9: '성별', 10: '자본이득', 11: '자본손실',
            12: '근무시간', 13:'고향', 14:'수입'
           }

df.rename(columns=titles, inplace=True)

In [36]:
df.head()

,나이,고용형태,가중치,최종학위,교육년수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,근무시간,고향,수입
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [37]:
# 이번에는 두개의 열을 .groupby() 에 리스트 형태로 넣어보자.
grouped = df.groupby(['가족내역할', '인종'])

In [38]:
grouped

In [39]:
grouped.first() # 그룹을 확인해보자

                                   나이              고용형태     가중치          최종학위  \
가족내역할          인종
Husband        Amer-Indian-Eskimo  34           Private  245487       7th-8th
               Asian-Pac-Islander  30         State-gov  141297     Bachelors
               Black               53           Private  234721          11th
               Other               28           Private  166481       7th-8th
               White               50  Self-emp-not-inc   83311     Bachelors
Not-in-family  Amer-Indian-Eskimo  35           Private  153790  Some-college
               Asian-Pac-Islander  28           Private   88419       HS-grad
               Black               49           Private  160187           9th
               Other               40           Private  237601     Bachelors
               White               39         State-gov   77516     Bachelors
Other-relative Amer-Indian-Eskimo  27           Private   23940       HS-grad
               Asian-Pac-Islander  33           Private  163003     Bachelors
               Black               42           Private  228456     Bachelors
               Other               33           Private  110978  Some-college
               White               79           Private  124744  Some-college
Own-child      Amer-Indian-Eskimo  20           Private   27337       HS-grad
               Asian-Pac-Islander  27           Private  116358  Some-college
               Black               20           Private  266015  Some-college
               Other               23                 ?  123983     Bachelors
               White               23           Private  122272     Bachelors
Unmarried      Amer-Indian-Eskimo  23                 ?   99399  Some-college
               Asian-Pac-Islander  44      Self-emp-inc   78374       Masters
               Black               54           Private  302146       HS-grad
               Other               65           Private  161400          11th
               White               32           Private  186824       HS-grad
Wife           Amer-Indian-Eskimo  29           Private  100405          10th
               Asian-Pac-Islander  30           Private  117747       HS-grad
               Black               28           Private  338409     Bachelors
               Other               25           Private   32275  Some-college
               White               37           Private  284582       Masters

                                   교육년수                   결혼유무  \
가족내역할          인종
Husband        Amer-Indian-Eskimo     4     Married-civ-spouse
               Asian-Pac-Islander    13     Married-civ-spouse
               Black                  7     Married-civ-spouse
               Other                  4     Married-civ-spouse
               White                 13     Married-civ-spouse
Not-in-family  Amer-Indian-Eskimo    10          Never-married
               Asian-Pac-Islander     9          Never-married
               Black                  5  Married-spouse-absent
               Other                 13          Never-married
               White                 13          Never-married
Other-relative Amer-Indian-Eskimo     9          Never-married
               Asian-Pac-Islander    13          Never-married
               Black                 13              Separated
               Other                 10               Divorced
               White                 10     Married-civ-spouse
Own-child      Amer-Indian-Eskimo     9          Never-married
               Asian-Pac-Islander    10          Never-married
               Black                 10          Never-married
               Other                 13          Never-married
               White                 13          Never-married
Unmarried      Amer-Indian-Eskimo    10          Never-married
               Asian-Pac-Islander    14               Divorced
               Black                  9              Separated
               Other                  7                Widowed
               White                  9          Never-married
Wife           Amer-Indian-Eskimo     6     Married-civ-spouse
               Asian-Pac-Islander     9     Married-civ-spouse
               Black                 13     Married-civ-spouse
               Other                 10     Married-civ-spouse
               White                 14     Married-civ-spouse

                                                 직업명      성별  자본이득  자본손실  \
가족내역할          인종
Husband        Amer-Indian-Eskimo   Transport-moving    Male     0     0
               Asian-Pac-Islander     Prof-specialty    Male     0     0
               Black               Handlers-cleaners    Male     0     0
               Other               Handlers-cleaners    Male     0  2179
               White                 Exec-managerial    Male     0     0
Not-in-family  Amer-Indian-Eskimo              Sales  Female     0     0
               Asian-Pac-Islander    Exec-managerial  Female     0     0
               Black                   Other-service  Female     0     0
               Other                           Sales  Female     0     0
               White                    Adm-clerical    Male  2174     0
Other-relative Amer-Indian-Eskimo  Handlers-cleaners    Male     0     0
               Asian-Pac-Islander    Exec-managerial  Female     0     0
               Black                   Other-service    Male     0     0
               Other                    Craft-repair  Female     0     0
               White                  Prof-specialty    Male     0     0
Own-child      Amer-Indian-Eskimo  Handlers-cleaners    Male     0     0
               Asian-Pac-Islander       Craft-repair    Male     0  1980
               Black                           Sales    Male     0     0
               Other                               ?    Male     0     0
               White                    Adm-clerical  Female     0     0
Unmarried      Amer-Indian-Eskimo                  ?  Female     0     0
               Asian-Pac-Islander    Exec-managerial  Female     0     0
               Black                   Other-service  Female     0     0
               Other                   Other-service    Male     0     0
               White               Machine-op-inspct    Male     0     0
Wife           Amer-Indian-Eskimo    Farming-fishing  Female     0     0
               Asian-Pac-Islander              Sales  Female     0  1573
               Black                  Prof-specialty  Female     0     0
               Other                 Exec-managerial  Female     0     0
               White                 Exec-managerial  Female     0     0

                                   근무시간             고향     수입
가족내역할          인종
Husband        Amer-Indian-Eskimo    45         Mexico  <=50K
               Asian-Pac-Islander    40          India   >50K
               Black                 40  United-States  <=50K
               Other                 40    Puerto-Rico  <=50K
               White                 13  United-States  <=50K
Not-in-family  Amer-Indian-Eskimo    40  United-States  <=50K
               Asian-Pac-Islander    40        England  <=50K
               Black                 16        Jamaica  <=50K
               Other                 55  United-States   >50K
               White                 40  United-States  <=50K
Other-relative Amer-Indian-Eskimo    40  United-States  <=50K
               Asian-Pac-Islander    40    Philippines  <=50K
               Black                 50  United-States  <=50K
               Other                 40  United-States  <=50K
               White                 20  United-States  <=50K
Own-child      Amer-Indian-Eskimo    48  United-States  <=50K
               Asian-Pac-Islander    40    Philippines  <=50K
               Black                 44  United-States  <=50K
               Other                 40  United-States  <=50K
               White                 30  United-States  <=50K
Unmarried      Amer-Indian-Eskimo    25  United-States  <=50K
               Asian-Pac-Islander    40  United-States  <=50K
               Black                 20  United-States  <=50K
               Other                 40  United-States  <=50K
               White                 40  United-States  <=50K
Wife           Amer-Indian-Eskimo    40  United-States  <=50K
               Asian-Pac-Islander    35              ?  <=50K
               Black                 40           Cuba  <=50K
               Other                 40  United-States  <=50K
               White                 40  United-States  <=50K

In [40]:
# 그룹이 하나였을때와 마찬가지로, 자료의 평균, 합, 카운트 등을 얻을 수 있다.
# 가족내역할과 인종별로 평균 교육햇수를 구해보자.
grouped['교육년수'].mean()
# 남편인데 인종이 에스키모일 경우 평균 교육기간은 9년이지만, 아내인데 인종이 에스키모일 경우 평균 교육기간은 10년이다.

가족내역할           인종
Husband         Amer-Indian-Eskimo     9.250000
                Asian-Pac-Islander    11.565854
                Black                  9.667660
                Other                  8.775000
                White                 10.339615
Not-in-family   Amer-Indian-Eskimo     9.432099
                Asian-Pac-Islander    11.046729
                Black                  9.653941
                Other                  9.534247
                White                 10.387088
Other-relative  Amer-Indian-Eskimo     8.769231
                Asian-Pac-Islander     9.914634
                Black                  8.902439
                Other                  8.750000
                White                  8.628242
Own-child       Amer-Indian-Eskimo     9.145833
                Asian-Pac-Islander    10.231214
                Black                  9.266667
                Other                  8.810811
                White                  9.494242
Unmarried       Amer-Indian-Eskimo     9.224138
                Asian-Pac-Islander    10.967033
                Black                  9.349805
                Other                  7.675676
                White                  9.723003
Wife            Amer-Indian-Eskimo    10.157895
                Asian-Pac-Islander    10.159420
                Black                  9.908497
                Other                  8.937500
                White                 10.566743
Name: 교육년수, dtype: float64

In [41]:
# 이번에는 노동시간의 합을 구해보자
grouped['근무시간'].sum()

가족내역할           인종
Husband         Amer-Indian-Eskimo      3935
                Asian-Pac-Islander     17835
                Black                  28156
                Other                   3449
                White                 528702
Not-in-family   Amer-Indian-Eskimo      3352
                Asian-Pac-Islander      8421
                Black                  32109
                Other                   2938
                White                 290327
Other-relative  Amer-Indian-Eskimo       512
                Asian-Pac-Islander      3014
                Black                   6007
                Other                   1053
                White                  25717
Own-child       Amer-Indian-Eskimo      1662
                Asian-Pac-Islander      6094
                Black                  18940
                Other                   1271
                White                 140642
Unmarried       Amer-Indian-Eskimo      2234
                Asian-Pac-Islander      3632
                Black                  29118
                Other                   1403
                White                  98362
Wife            Amer-Indian-Eskimo       760
                Asian-Pac-Islander      2696
                Black                   5703
                Other                    582
                White                  48058
Name: 근무시간, dtype: int64

In [42]:
# 값을 정렬해서 보고싶다면, .sort_values() 를 적용할 수 있다.
grouped['근무시간'].sum().sort_values()

가족내역할           인종
Other-relative  Amer-Indian-Eskimo       512
Wife            Other                    582
                Amer-Indian-Eskimo       760
Other-relative  Other                   1053
Own-child       Other                   1271
Unmarried       Other                   1403
Own-child       Amer-Indian-Eskimo      1662
Unmarried       Amer-Indian-Eskimo      2234
Wife            Asian-Pac-Islander      2696
Not-in-family   Other                   2938
Other-relative  Asian-Pac-Islander      3014
Not-in-family   Amer-Indian-Eskimo      3352
Husband         Other                   3449
Unmarried       Asian-Pac-Islander      3632
Husband         Amer-Indian-Eskimo      3935
Wife            Black                   5703
Other-relative  Black                   6007
Own-child       Asian-Pac-Islander      6094
Not-in-family   Asian-Pac-Islander      8421
Husband         Asian-Pac-Islander     17835
Own-child       Black                  18940
Other-relative  White                  25717
Husband         Black                  28156
Unmarried       Black                  29118
Not-in-family   Black                  32109
Wife            White                  48058
Unmarried       White                  98362
Own-child       White                 140642
Not-in-family   White                 290327
Husband         White                 528702
Name: 근무시간, dtype: int64

In [43]:
# 각 그룹마다 자료가 몇개있는지 보고싶다면 .count() 를 사용할 수 있다. 이때, 자료에 결측값이 없다면 어떤 열을 사용해도 같은 값을 얻는다.
grouped['고향'].count()
# 백인 남편에 대한 자료가 가장 많다.

가족내역할           인종
Husband         Amer-Indian-Eskimo       92
                Asian-Pac-Islander      410
                Black                   671
                Other                    80
                White                 11940
Not-in-family   Amer-Indian-Eskimo       81
                Asian-Pac-Islander      214
                Black                   812
                Other                    73
                White                  7125
Other-relative  Amer-Indian-Eskimo       13
                Asian-Pac-Islander       82
                Black                   164
                Other                    28
                White                   694
Own-child       Amer-Indian-Eskimo       48
                Asian-Pac-Islander      173
                Black                   555
                Other                    37
                White                  4255
Unmarried       Amer-Indian-Eskimo       58
                Asian-Pac-Islander       91
                Black                   769
                Other                    37
                White                  2491
Wife            Amer-Indian-Eskimo       19
                Asian-Pac-Islander       69
                Black                   153
                Other                    16
                White                  1311
Name: 고향, dtype: int64

#### 숫자 자료형

지금까지는 그룹이 문자열로 표현된 경우만 살펴봤다. 이번에는 숫자 자료형을 groupby 해보자. 숫자 자료형을 groupby 하면, 각 숫자가 key 가 되어 그룹이 만들어진다.

예시로 문자열 자료형인 '성별'과 숫자 자료형인 '교육햇수'를 groupby 해보자.

In [44]:
grouped2 = df.groupby(['성별', '교육년수'])

In [45]:
grouped2.first()

             나이              고용형태     가중치          최종학위  \
성별     교육년수
Female 1     53         Local-gov  140359     Preschool
       2     68                 ?   38317       1st-4th
       3     22           Private  399087       5th-6th
       4     45           Private  433665       7th-8th
       5     49           Private  160187           9th
       6     17                 ?  304873          10th
       7     18           Private  309634          11th
       8     58  Self-emp-not-inc  211547          12th
       9     54           Private  302146       HS-grad
       10    25           Private   32275  Some-college
       11    27           Private  163127     Assoc-voc
       12    48           Private  171095    Assoc-acdm
       13    28           Private  338409     Bachelors
       14    37           Private  284582       Masters
       15    47           Private   51835   Prof-school
       16    43       Federal-gov  410867     Doctorate
Male   1     51         Local-gov  241843     Preschool
       2     64                 ?  187656       1st-4th
       3     46           Private  216666       5th-6th
       4     34           Private  245487       7th-8th
       5     35       Federal-gov   76845           9th
       6     67                 ?  212759          10th
       7     53           Private  234721          11th
       8     35           Private   92440          12th
       9     38           Private  215646       HS-grad
       10    37           Private  280464  Some-college
       11    40           Private  121772     Assoc-voc
       12    32           Private  205019    Assoc-acdm
       13    39         State-gov   77516     Bachelors
       14    33           Private  202051       Masters
       15    38           Private   65324   Prof-school
       16    40           Private  193524     Doctorate

                              결혼유무                직업명           가족내역할  \
성별     교육년수
Female 1             Never-married  Machine-op-inspct   Not-in-family
       2                  Divorced                  ?   Not-in-family
       3        Married-civ-spouse  Machine-op-inspct  Other-relative
       4                 Separated      Other-service       Unmarried
       5     Married-spouse-absent      Other-service   Not-in-family
       6             Never-married                  ?       Own-child
       7             Never-married      Other-service       Own-child
       8                  Divorced              Sales   Not-in-family
       9                 Separated      Other-service       Unmarried
       10       Married-civ-spouse    Exec-managerial            Wife
       11       Married-civ-spouse       Adm-clerical            Wife
       12                 Divorced    Exec-managerial       Unmarried
       13       Married-civ-spouse     Prof-specialty            Wife
       14       Married-civ-spouse    Exec-managerial            Wife
       15       Married-civ-spouse     Prof-specialty            Wife
       16            Never-married     Prof-specialty   Not-in-family
Male   1        Married-civ-spouse      Other-service         Husband
       2                  Divorced                  ?   Not-in-family
       3        Married-civ-spouse  Machine-op-inspct         Husband
       4        Married-civ-spouse   Transport-moving         Husband
       5        Married-civ-spouse    Farming-fishing         Husband
       6        Married-civ-spouse                  ?         Husband
       7        Married-civ-spouse  Handlers-cleaners         Husband
       8                  Divorced       Craft-repair   Not-in-family
       9                  Divorced  Handlers-cleaners   Not-in-family
       10       Married-civ-spouse    Exec-managerial         Husband
       11       Married-civ-spouse       Craft-repair         Husband
       12            Never-married              Sales   Not-in-family
       13            Never-married       Adm-clerical   Not-in-family
       14       Married-civ-spouse     Prof-specialty         Husband
       15       Married-civ-spouse     Prof-specialty         Husband
       16       Married-civ-spouse     Prof-specialty         Husband

                             인종   자본이득  자본손실  근무시간             고향     수입
성별     교육년수
Female 1                  White      0     0    35  United-States  <=50K
       2                  White      0     0    20  United-States  <=50K
       3                  White      0     0    40         Mexico  <=50K
       4                  White      0     0    40         Mexico  <=50K
       5                  Black      0     0    16        Jamaica  <=50K
       6                  White  34095     0    32  United-States  <=50K
       7                  White      0     0    22  United-States  <=50K
       8                  White      0     0    52  United-States  <=50K
       9                  Black      0     0    20  United-States  <=50K
       10                 Other      0     0    40  United-States  <=50K
       11                 White      0     0    35  United-States  <=50K
       12                 White      0     0    40        England  <=50K
       13                 Black      0     0    40           Cuba  <=50K
       14                 White      0     0    40  United-States  <=50K
       15                 White      0  1902    60       Honduras   >50K
       16                 White      0     0    50  United-States   >50K
Male   1                  White      0     0    40  United-States  <=50K
       2                  White      0     0    40  United-States  <=50K
       3                  White      0     0    40         Mexico  <=50K
       4     Amer-Indian-Eskimo      0     0    45         Mexico  <=50K
       5                  Black      0     0    40  United-States  <=50K
       6                  White      0     0     2  United-States  <=50K
       7                  Black      0     0    40  United-States  <=50K
       8                  White      0     0    50  United-States   >50K
       9                  White      0     0    40  United-States  <=50K
       10                 Black      0     0    80  United-States   >50K
       11    Asian-Pac-Islander      0     0    40              ?   >50K
       12                 Black      0     0    50  United-States  <=50K
       13                 White   2174     0    40  United-States  <=50K
       14                 White      0     0    50  United-States  <=50K
       15                 White      0     0    40  United-States   >50K
       16                 White      0     0    60  United-States   >50K

In [47]:
# grouped2 의 평균 나이를 정렬해서 살펴보자.
grouped2['근무시간'].mean().sort_values()
# 교육햇수가 15, 16 일때, 성별 상관없이 평균 노동시간이 많은것을 알 수 있다.

성별      교육년수
Female  7       29.821759
        8       31.791667
        1       31.875000
        2       31.978261
        6       32.111864
        5       33.916667
        10      34.574840
        3       36.047619
        4       36.200000
Male    7       36.312248
Female  9       36.577286
        12      37.358670
Male    8       37.768166
Female  11      37.830000
Male    1       38.828571
Female  13      39.329216
Male    6       39.336991
        5       39.651351
        3       39.859438
        4       40.409465
        2       40.622951
Female  14      41.113806
Male    10      41.528428
        9       42.481367
        12      42.554180
        11      43.753968
        13      44.037473
Female  15      44.793478
Male    14      45.065712
        16      46.886850
Female  16      47.302326
Male    15      47.925620
Name: 근무시간, dtype: float64

In [48]:
# 지금까지는 자료를 Series 형태로 봤다. [[]] 를 사용하면, 이를 데이터 프레임으로 바꿀 수 있다.
grouped2[['근무시간']].mean().head()

                  근무시간
성별     교육년수
Female 1     31.875000
       2     31.978261
       3     36.047619
       4     36.200000
       5     33.916667

In [49]:
# 성별과 교육년수별로 근무시간 합을 구한후, 그 합들의 그룹별 평균을 구할 수 있다.
grouped2['근무시간'].sum() # 먼저 성별과 교육년수별 근무시간의 합을 구해보자.

성별      교육년수
Female  1          510
        2         1471
        3         3028
        4         5792
        5         4884
        6         9473
        7        12883
        8         4578
        9       123997
        10       97017
        11       18915
        12       15728
        13       63674
        14       22037
        15        4121
        16        4068
Male    1         1359
        2         4956
        3         9925
        4        19639
        5        14671
        6        25097
        7        26980
        8        10915
        9       302085
        10      186255
        11       38591
        12       27490
        13      164524
        14       53493
        15       23196
        16       15332
Name: 근무시간, dtype: int64

In [50]:
# 뒤에 .groupby(level=0).mean() 를 붙이면 성별 평균을 볼 수 있다.
grouped2['근무시간'].sum().groupby(level=0).mean()

성별
Female    24511.00
Male      57781.75
Name: 근무시간, dtype: float64

In [51]:
# 만약 총 근무시간을 교육년수 평균으로 보고싶다면, level=1 라고 바꿔주면 된다.
grouped2['근무시간'].sum().groupby(level=1).mean()

교육년수
1        934.5
2       3213.5
3       6476.5
4      12715.5
5       9777.5
6      17285.0
7      19931.5
8       7746.5
9     213041.0
10    141636.0
11     28753.0
12     21609.0
13    114099.0
14     37765.0
15     13658.5
16      9700.0
Name: 근무시간, dtype: float64

In [52]:
# .reset_index()로 다중 인덱스를 풀 수 있다.
grouped2['근무시간'].mean().reset_index().head()

       성별  교육년수       근무시간
0  Female     1  31.875000
1  Female     2  31.978261
2  Female     3  36.047619
3  Female     4  36.200000
4  Female     5  33.916667

In [53]:
# .unstack()로 다중 인덱스를 가로와 세로축으로 나타낼 수 있다.
grouped2['근무시간'].mean().unstack()

교육년수,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
성별,,,,,,,,,,,,,,,,
Female,31.875000,31.978261,36.047619,36.200000,33.916667,32.111864,29.821759,31.791667,36.577286,34.574840,37.830000,37.35867,39.329216,41.113806,44.793478,47.302326
Male,38.828571,40.622951,39.859438,40.409465,39.651351,39.336991,36.312248,37.768166,42.481367,41.528428,43.753968,42.55418,44.037473,45.065712,47.925620,46.886850

### 10.2.3. apply
.apply() 와 .map() 등을 이용해 데이터 프레임의 열, 행, 값에 함수를 적용할 수 있다.

예제로 산불 데이터를 사용하자.

In [54]:
import pandas as pd
df = pd.read_excel('forestfires.xlsx')
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

#### 함수 소개
판다스에서 함수를 일괄 적용하는 방법에 크게 세가지 방식이 있다.

series.map(): map 은 Series의 값 단위로 함수를 적용한다.

df.apply(): apply 는 데이터 프레임의 행과 열 단위에 함수를 적용한다.

df.applymap(): applymap 은 데이터 프레임의 값 단위에 함수를 적용한다.

In [55]:
# .map() 은 Series 에 적용할 수 있다.
s = df['ISI'] # 먼저, ISI 열을 불러와 연습해보자. s 는 Series 다.
s.head()

0    5.1
1    6.7
2    6.7
3    9.0
4    9.6
Name: ISI, dtype: float64

In [57]:
# 이젠, 적용시킬 함수를 만들어보자. 값을 10으로 나누는 div_10 함수를 만들어보자.
def div_10(x):
    return x / 10

In [58]:
div_10(30) # 잘 작동하는지 확인해보자.

3.0

In [59]:
# 다음으로는 함수를 .map() 안에 넘겨줘 s 에 적용해보자.
s.map(div_10).head()

0    0.51
1    0.67
2    0.67
3    0.90
4    0.96
Name: ISI, dtype: float64

In [60]:
# x 마다 10 을 나누는 람다 함수를 .map() 에 넘겨준다.
s.map(lambda x: x / 10).head()

0    0.51
1    0.67
2    0.67
3    0.90
4    0.96
Name: ISI, dtype: float64

In [61]:
# apply 는 각 값을 함수의 인수로 넘기는 것이 아니라, 열 혹은 행을 통으로 함수의 인수로 넘긴다.
for column_name, data in df.iteritems():
    print(column_name)
    print(data.head())
    break

X
0    7
1    7
2    7
3    8
4    8
Name: X, dtype: int64

In [62]:
# 확인해보기 위해, 인수를 프린트 하는 함수 see_x 를 만들어 apply 에 넣어보자.
def see_x(x):
    print(x.head())

In [63]:
# 간략하게 보기 위해 wind, rain, area 열에만 적용해보자.
df[['wind', 'rain', 'area']].apply(see_x)

0    6.7
1    0.9
2    1.3
3    4.0
4    1.8
Name: wind, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.2
4    0.0
Name: rain, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: area, dtype: float64

wind    None
rain    None
area    None
dtype: object

In [64]:
# max_min 함수를 만든다. .max()와 .min() 으로 최대, 최소값을 구한다.
def max_min(x):
    return x.max() - x.min()

In [65]:
df[['wind', 'rain', 'area']].apply(max_min)

wind       9.00
rain       6.40
area    1090.84
dtype: float64

In [66]:
# 이번에는 axis=1 일 경우를 살펴보자.
# axis=1 일때 작동방식을 살펴보기 위해 .iterrows() 를 살펴보자. .iterrows() 는 .iteritems()와 반대로 각 행의 위치와 행 정보를 generator 로 만들어준다.
for i, item in df.iterrows():  # 위치, 행 정보
    print(i)
    print(item)
    break

0
X           7
Y           5
month     mar
day       fri
FFMC     86.2
DMC      26.2
DC       94.3
ISI       5.1
temp      8.2
RH         51
wind      6.7
rain        0
area        0
Name: 0, dtype: object

In [67]:
# 위에서 만든 see_x 함수를 apply 에 적용해보자.
# 간략하게 보기 위해 첫 다섯 행만 살펴보자.
df.iloc[:5].apply(see_x, axis=1)

X           7
Y           5
month     mar
day       fri
FFMC     86.2
Name: 0, dtype: object
X           7
Y           4
month     oct
day       tue
FFMC     90.6
Name: 1, dtype: object
X           7
Y           4
month     oct
day       sat
FFMC     90.6
Name: 2, dtype: object
X           8
Y           6
month     mar
day       fri
FFMC     91.7
Name: 3, dtype: object
X           8
Y           6
month     mar
day       sun
FFMC     89.3
Name: 4, dtype: object

0    None
1    None
2    None
3    None
4    None
dtype: object

In [68]:
df[['wind', 'rain', 'area']].head() # applymap 은 데이터 프레임의 각 값에 함수를 적용한다.

   wind  rain  area
0   6.7   0.0   0.0
1   0.9   0.0   0.0
2   1.3   0.0   0.0
3   4.0   0.2   0.0
4   1.8   0.0   0.0

In [69]:
# 먼저 퍼센트 표시를 붙이는 함수 add_percent 를 만든다.
def add_percent(x):
    return str(x) + '%'

In [70]:
# 함수가 잘 작동하는지 확인한다
add_percent(99)

'99%'

In [71]:
# 다음으로는 wind, rain, area 에 .applymap 을 사용해 add_percent 함수를 적용한다.
df[['wind', 'rain', 'area']].applymap(add_percent).head()

   wind  rain  area
0  6.7%  0.0%  0.0%
1  0.9%  0.0%  0.0%
2  1.3%  0.0%  0.0%
3  4.0%  0.2%  0.0%
4  1.8%  0.0%  0.0%

In [72]:
# 같은 함수를 람다로 표현할 수 있다.
df[['wind', 'rain', 'area']].applymap(lambda x: str(x) + '%').head()

   wind  rain  area
0  6.7%  0.0%  0.0%
1  0.9%  0.0%  0.0%
2  1.3%  0.0%  0.0%
3  4.0%  0.2%  0.0%
4  1.8%  0.0%  0.0%

### 10.2.4. agg
agg 는 그룹 연산을 위한 메써드이다.

각 열에 적용하고 싶은 함수가 있을 때, agg 를 사용한다.

예시로 산불 데이터를 사용하자.

In [73]:
import pandas as pd

In [74]:
df = pd.read_excel('forestfires.xlsx')

In [75]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [76]:
# .agg() 에 max 함수를 넘겨, 각 열의 최대값을 구해보자.
df.agg(max)
# 열 별 최대값이 구해졌다.

X              9
Y              9
month        sep
day          wed
FFMC        96.2
DMC        291.3
DC         860.6
ISI         56.1
temp        33.3
RH           100
wind         9.4
rain         6.4
area     1090.84
dtype: object

In [77]:
# 문자열로 'max' 를 넘겨줘도 같은 결과를 구한다.
df.agg('max')

X              9
Y              9
month        sep
day          wed
FFMC        96.2
DMC        291.3
DC         860.6
ISI         56.1
temp        33.3
RH           100
wind         9.4
rain         6.4
area     1090.84
dtype: object

In [78]:
# 편의를 위해 연속변수들만 따로 모아 forest 라고 저장하자.
forest = df[['X', 'Y', 'temp', 'wind', 'rain', 'area']]

In [79]:
# 이번에는 sum, min, max 함수를 .agg() 에 리스트 형태로 넘겨보자.
forest.agg([sum, min, max])
# 세 함수가 모든 열에 적용되었다

        X     Y    temp    wind  rain     area
sum  2414  2223  9765.7  2077.1  11.2  6642.05
min     1     2     2.2     0.4   0.0     0.00
max     9     9    33.3     9.4   6.4  1090.84

In [80]:
# 최대 온도와 최소 강수량을 구하도록 사전을 만들어 넘겨보자.
forest.agg({'temp': max, 'rain': min})

temp    33.3
rain     0.0
dtype: float64

In [81]:
# 온도는 최대, 최소 값을 모두 구하고 강수량은 최대값만 구해보자.
forest.agg({'temp':[min, max], 'rain':max})

     temp  rain
max  33.3   6.4
min   2.2   NaN

In [82]:
# 최대값에서 최소값을 빼는 max_min 함수를 적용해보자.
def max_min(x):
    return max(x) - min(x)

In [83]:
forest.agg(max_min)

X          8.00
Y          7.00
temp      31.10
wind       9.00
rain       6.40
area    1090.84
dtype: float64

In [84]:
# 열마다 가장 많이 등장하는 값과 빈도를 구해주는 max_count 함수를 만들어보자.
def max_count(x):
    max_index = x.value_counts().idxmax()  # 가장 자주 등장하는 값
    max_value = x.value_counts().max()  # 등장 빈도
    return max_index, max_value

In [85]:
forest.agg(max_count)

X        (4.0, 91)
Y       (4.0, 203)
temp     (17.4, 8)
wind     (2.2, 53)
rain    (0.0, 509)
area    (0.0, 247)
dtype: object

In [86]:
# groupby 로 그룹을 만든 후, agg 를 사용할 수 있다.
grouped = forest.groupby('X') # 예시로 X 값을 그룹으로 잡아보자.

In [87]:
grouped.agg(max) # 각 그룹당 최고값을 구하도록 .agg(max) 를 구해보자.

   Y  temp  wind  rain     area
X
1  5  32.4   8.5   0.0   212.88
2  5  33.1   9.4   0.0   200.94
3  6  32.3   8.5   0.0    35.88
4  6  32.6   8.5   0.4   154.88
5  6  27.6   8.0   1.4    24.24
6  6  33.3   9.4   0.0  1090.84
7  6  27.3   9.4   6.4   278.53
8  8  31.0   8.9   0.8   746.28
9  9  30.2   4.5   0.0   105.66

In [89]:
# 온도는 최고값을, 강수량은 총 강수량과 최대강수량을 구해보자.
forest.groupby('X').agg({'temp':max, 'rain':[sum, max]})
# X 좌표마다 최고온도, 강수량의 합과 최고값을 볼 수 있다.

   temp rain
    max  sum  max
X
1  32.4  0.0  0.0
2  33.1  0.0  0.0
3  32.3  0.0  0.0
4  32.6  0.4  0.4
5  27.6  1.4  1.4
6  33.3  0.0  0.0
7  27.3  8.4  6.4
8  31.0  1.0  0.8
9  30.2  0.0  0.0

### 10.2.5. pivot table
엑셀에서 피봇 테이블을 판다스로 구현해보자.

피봇 테이블이란, 열과 행의 그룹들을 값으로 보는 방식을 의미한다.

df.pivot_table(index=행에 두고 싶은 열, columns=열에 두고 싶은 열, values=값에 두고 싶은 열)

산불 데이터를 예시로 피봇 테이블에 대해 알아보자.

In [90]:
import pandas as pd

In [91]:
forest = pd.read_excel('forestfires.xlsx')

In [92]:
forest.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [94]:
# 월별 요일별 온도를 피봇 테이블로 나타내보자. 행에는 월을, 열에는 요일을, 그리고 값에는 온도를 나타내자.
forest.pivot_table(index='month', columns='day', values='temp')
# 피봇 테이블의 기본적으로 평균값을 구해준다.

day,fri,mon,sat,sun,thu,tue,wed
month,,,,,,,
apr,16.700000,10.900000,9.300000,14.900000,5.800000,NaN,15.200000
aug,21.238095,22.693333,20.503448,21.257500,21.407692,21.842857,23.228000
dec,2.200000,4.600000,NaN,4.800000,5.100000,5.100000,5.100000
feb,11.680000,8.900000,11.725000,8.875000,6.700000,4.850000,8.800000
jan,NaN,NaN,5.300000,5.200000,NaN,NaN,NaN
jul,17.033333,21.575000,22.450000,24.360000,29.200000,22.500000,15.366667
jun,20.533333,18.033333,17.550000,18.225000,24.550000,NaN,25.200000
mar,14.000000,11.783333,15.430000,10.628571,11.420000,15.100000,12.450000
may,18.000000,NaN,11.300000,NaN,NaN,NaN,NaN
nov,NaN,NaN,NaN,NaN,NaN,11.800000,NaN
oct,11.300000,17.175000,16.933333,16.600000,NaN,19.850000,18.050000
sep,18.586842,18.125000,21.524000,20.437037,20.390476,18.721053,20.407143

In [95]:
# 결측값이 있어 NaN 이 자주 보인다. fill_value=0 이라는 옵션을 넘겨 NaN 을 0 으로 바꿔보자.
forest.pivot_table(index='month', columns='day', values='temp', fill_value=0)
# 결측값이 모두 0 으로 처리되었다.

day,fri,mon,sat,sun,thu,tue,wed
month,,,,,,,
apr,16.700000,10.900000,9.300000,14.900000,5.800000,0.000000,15.200000
aug,21.238095,22.693333,20.503448,21.257500,21.407692,21.842857,23.228000
dec,2.200000,4.600000,0.000000,4.800000,5.100000,5.100000,5.100000
feb,11.680000,8.900000,11.725000,8.875000,6.700000,4.850000,8.800000
jan,0.000000,0.000000,5.300000,5.200000,0.000000,0.000000,0.000000
jul,17.033333,21.575000,22.450000,24.360000,29.200000,22.500000,15.366667
jun,20.533333,18.033333,17.550000,18.225000,24.550000,0.000000,25.200000
mar,14.000000,11.783333,15.430000,10.628571,11.420000,15.100000,12.450000
may,18.000000,0.000000,11.300000,0.000000,0.000000,0.000000,0.000000
nov,0.000000,0.000000,0.000000,0.000000,0.000000,11.800000,0.000000
oct,11.300000,17.175000,16.933333,16.600000,0.000000,19.850000,18.050000
sep,18.586842,18.125000,21.524000,20.437037,20.390476,18.721053,20.407143

In [96]:
# 평균값이 아닌, 합을 구하고 싶다면 aggfunc=sum 이라는 옵션을 넘겨줄 수 있다.
forest.pivot_table(index='month', columns='day', values='temp', fill_value=0, aggfunc=sum)

day      fri    mon    sat    sun    thu    tue    wed
month
apr     16.7   10.9    9.3   44.7   11.6    0.0   15.2
aug    446.0  340.4  594.6  850.3  556.6  611.6  580.7
dec      2.2   18.4    0.0    4.8    5.1    5.1    5.1
feb     58.4   26.7   46.9   35.5    6.7    9.7    8.8
jan      0.0    0.0    5.3    5.2    0.0    0.0    0.0
jul     51.1   86.3  179.6  121.8   87.6  135.0   46.1
jun     61.6   54.1   35.1   72.9   49.1    0.0   75.6
mar    154.0  141.4  154.3   74.4   57.1   75.5   49.8
may     18.0    0.0   11.3    0.0    0.0    0.0    0.0
nov      0.0    0.0    0.0    0.0    0.0   11.8    0.0
oct     11.3   68.7   50.8   49.8    0.0   39.7   36.1
sep    706.3  507.5  538.1  551.8  428.2  355.7  285.7

In [97]:
# 마찬가지로 최소값을 구하고 싶다면 aggfunc=min 이라는 옵션을 넘겨줄 수 있다.
forest.pivot_table(index='month', columns='day', values='temp', fill_value=0, aggfunc=min)

day     fri   mon   sat   sun   thu   tue   wed
month
apr    16.7  10.9   9.3  13.4   5.8   0.0  15.2
aug    11.2   8.0   5.1  10.4  16.2  14.4  16.6
dec     2.2   4.6   0.0   4.8   5.1   5.1   5.1
feb     7.5   5.3   4.6   4.2   6.7   4.6   8.8
jan     0.0   0.0   5.3   5.2   0.0   0.0   0.0
jul    13.4  17.9  16.6  18.2  27.2  17.1  12.6
jun    19.2  14.3  10.6  14.3  22.7   0.0  19.6
mar     8.2   8.3  11.6   5.5   5.3  14.1   8.9
may    18.0   0.0  11.3   0.0   0.0   0.0   0.0
nov     0.0   0.0   0.0   0.0   0.0  11.8   0.0
oct    11.3  16.1  14.6  13.8   0.0  18.0  15.9
sep    10.1   9.8  15.4  12.2  12.9  13.1  10.5

In [98]:
# 만들어 놓은 피봇 테이블에 X 좌표도 추가해서 표현할 수 있다. 행에 'month' 를 ['month', 'day'] 로 바꾸고 columns='X' 라고 바꿔보자.
forest.pivot_table(index=['month', 'day'], columns='X', values='temp', fill_value=0)

X                  1          2          3          4      5          6  \
month day
apr   fri   0.000000   0.000000   0.000000  16.700000   0.00   0.000000
      mon   0.000000   0.000000   0.000000   0.000000   0.00  10.900000
      sat   0.000000   0.000000   0.000000   0.000000   0.00   9.300000
      sun   0.000000   0.000000   0.000000   0.000000  17.60  13.700000
      thu   0.000000   0.000000   0.000000   0.000000   0.00   5.800000
      wed   0.000000   0.000000   0.000000   0.000000   0.00  15.200000
aug   fri  21.857143  23.600000  11.200000  21.800000  21.10  19.450000
      mon   0.000000  27.475000  13.700000  32.600000   0.00  23.900000
      sat  21.860000  21.825000  19.100000  19.900000   0.00  22.750000
      sun  18.700000  22.430000  21.000000  20.275000  22.85  19.100000
      thu  24.366667  20.150000  18.200000  22.466667  20.30  22.200000
      tue  20.100000  22.537500  22.566667  19.580000  22.60  26.350000
      wed  19.933333  23.900000  21.700000  23.733333   0.00  20.700000
dec   fri   0.000000   0.000000   0.000000   2.200000   0.00   0.000000
      mon   0.000000   0.000000   4.600000   4.600000   0.00   0.000000
      sun   0.000000   0.000000   0.000000   4.800000   0.00   0.000000
      thu   0.000000   0.000000   0.000000   5.100000   0.00   0.000000
      tue   0.000000   0.000000   0.000000   0.000000   0.00   5.100000
      wed   0.000000   0.000000   0.000000   0.000000   0.00   0.000000
feb   fri   0.000000  12.300000   0.000000   0.000000   7.50  14.700000
      mon   0.000000  13.900000   0.000000   0.000000   0.00   5.300000
      sat   0.000000   4.600000  12.700000  14.800000   0.00   0.000000
      sun   0.000000   0.000000   0.000000  10.100000  12.40   4.200000
      thu   0.000000   0.000000   0.000000   0.000000   0.00   0.000000
      tue   0.000000   0.000000   0.000000   0.000000   0.00   4.850000
      wed   0.000000   0.000000   8.800000   0.000000   0.00   0.000000
jan   sat   0.000000   5.300000   0.000000   0.000000   0.00   0.000000
      sun   0.000000   0.000000   0.000000   5.200000   0.00   0.000000
jul   fri  14.800000  13.400000   0.000000  22.900000   0.00   0.000000
      mon   0.000000   0.000000  17.900000   0.000000   0.00  23.000000
...              ...        ...        ...        ...    ...        ...
      wed   0.000000   0.000000  14.200000   0.000000  19.30   0.000000
jun   fri   0.000000   0.000000  19.200000   0.000000   0.00  23.200000
      mon   0.000000   0.000000   0.000000   0.000000   0.00  19.900000
      sat   0.000000   0.000000   0.000000   0.000000   0.00  10.600000
      sun   0.000000   0.000000   0.000000   0.000000   0.00  14.300000
      thu   0.000000  22.700000   0.000000  26.400000   0.00   0.000000
      wed   0.000000   0.000000   0.000000   0.000000   0.00   0.000000
mar   fri   0.000000   0.000000  18.800000  14.850000  15.60  13.150000
      mon   8.300000   0.000000   9.800000  11.950000  13.20  12.700000
      sat   0.000000   0.000000  14.733333  17.000000  15.10  15.300000
      sun   0.000000   8.500000   0.000000  10.600000   0.00  12.400000
      thu   0.000000   0.000000   0.000000  18.200000  11.60   9.100000
      tue   0.000000  15.200000  15.400000  14.100000   0.00   0.000000
      wed   0.000000   0.000000  10.050000   0.000000   0.00  14.850000
may   fri   0.000000   0.000000   0.000000  18.000000   0.00   0.000000
      sat   0.000000   0.000000   0.000000   0.000000   0.00  11.300000
nov   tue   0.000000   0.000000   0.000000   0.000000   0.00  11.800000
oct   fri   0.000000   0.000000   0.000000   0.000000   0.00   0.000000
      mon   0.000000   0.000000   0.000000   0.000000   0.00   0.000000
      sat   0.000000   0.000000   0.000000  18.400000   0.00   0.000000
      sun   0.000000  15.400000  20.600000  13.800000   0.00   0.000000
      tue   0.000000   0.000000   0.000000   0.000000   0.00  21.700000
      wed   0.000000   0.000000  15.900000   0.000000   0.00   0.000000
sep   fri  20.100000  19.600000  18.250000  18.650000  16.15  19.100000
      mon  18.200000  19.833333  17.250000  14.966667  16.90  18.250000
      sat  25.366667  23.633333  24.200000  19.640000  24.10  20.771429
      sun  22.066667  17.700000  21.380000  20.016667   0.00  21.766667
      thu  21.525000   0.000000  17.850000  21.071429  21.60  17.750000
      tue  20.700000  17.600000  15.900000  16.500000   0.00  19.180000
      wed   0.000000  20.050000  18.500000  20.540000  23.90  25.350000

X                  7          8     9
month day
apr   fri   0.000000   0.000000   0.0
      mon   0.000000   0.000000   0.0
      sat   0.000000   0.000000   0.0
      sun  13.400000   0.000000   0.0
      thu   0.000000   0.000000   0.0
      wed   0.000000   0.000000   0.0
aug   fri  23.300000  21.000000  25.0
      mon  17.700000  21.483333   0.0
      sat  18.983333  20.075000   0.0
      sun  19.200000  22.257143   0.0
      thu  21.400000  21.666667  20.5
      tue  24.450000  18.700000   0.0
      wed   0.000000  25.216667   0.0
dec   fri   0.000000   0.000000   0.0
      mon   0.000000   0.000000   0.0
      sun   0.000000   0.000000   0.0
      thu   0.000000   0.000000   0.0
      tue   0.000000   0.000000   0.0
      wed   0.000000   5.100000   0.0
feb   fri   8.200000   0.000000  15.7
      mon   7.500000   0.000000   0.0
      sat   0.000000   0.000000   0.0
      sun   8.800000   0.000000   0.0
      thu   0.000000   0.000000   6.7
      tue   0.000000   0.000000   0.0
      wed   0.000000   0.000000   0.0
jan   sat   0.000000   0.000000   0.0
      sun   0.000000   0.000000   0.0
jul   fri   0.000000   0.000000   0.0
      mon  22.600000   0.000000  22.8
...              ...        ...   ...
      wed  12.600000   0.000000   0.0
jun   fri   0.000000   0.000000   0.0
      mon   0.000000  14.300000   0.0
      sat   0.000000   0.000000  24.5
      sun  21.600000  15.400000   0.0
      thu   0.000000   0.000000   0.0
      wed   0.000000  19.600000  28.0
mar   fri   8.200000  12.850000   0.0
      mon  13.550000   0.000000   0.0
      sat   0.000000   0.000000   0.0
      sun  11.500000  11.450000   0.0
      thu   0.000000   0.000000   0.0
      tue   0.000000   0.000000   0.0
      wed   0.000000   0.000000   0.0
may   fri   0.000000   0.000000   0.0
      sat   0.000000   0.000000   0.0
nov   tue   0.000000   0.000000   0.0
oct   fri  11.300000   0.000000   0.0
      mon  16.450000  17.900000   0.0
      sat  16.200000   0.000000   0.0
      sun   0.000000   0.000000   0.0
      tue  18.000000   0.000000   0.0
      wed   0.000000  20.200000   0.0
sep   fri  18.914286  20.700000   0.0
      mon  19.350000  18.100000   0.0
      sat  20.350000  17.800000   0.0
      sun  18.733333  17.800000   0.0
      thu  19.400000  23.450000   0.0
      tue  20.700000  18.650000  24.3
      wed  12.950000   0.000000   0.0

[64 rows x 9 columns]

In [99]:
# 한눈에 보기 편하게 index='X'라고 두고, columns=['month', 'day'] 라고 표현하자.
forest.pivot_table(index='X', columns=['month', 'day'], values='temp', fill_value=0)

month   apr                                    aug                        \
day     fri   mon  sat   sun  thu   wed        fri        mon        sat
X
1       0.0   0.0  0.0   0.0  0.0   0.0  21.857143   0.000000  21.860000
2       0.0   0.0  0.0   0.0  0.0   0.0  23.600000  27.475000  21.825000
3       0.0   0.0  0.0   0.0  0.0   0.0  11.200000  13.700000  19.100000
4      16.7   0.0  0.0   0.0  0.0   0.0  21.800000  32.600000  19.900000
5       0.0   0.0  0.0  17.6  0.0   0.0  21.100000   0.000000   0.000000
6       0.0  10.9  9.3  13.7  5.8  15.2  19.450000  23.900000  22.750000
7       0.0   0.0  0.0  13.4  0.0   0.0  23.300000  17.700000  18.983333
8       0.0   0.0  0.0   0.0  0.0   0.0  21.000000  21.483333  20.075000
9       0.0   0.0  0.0   0.0  0.0   0.0  25.000000   0.000000   0.000000

month             ...     oct                    sep                        \
day          sun  ...     sun   tue   wed        fri        mon        sat
X                 ...
1      18.700000  ...     0.0   0.0   0.0  20.100000  18.200000  25.366667
2      22.430000  ...    15.4   0.0   0.0  19.600000  19.833333  23.633333
3      21.000000  ...    20.6   0.0  15.9  18.250000  17.250000  24.200000
4      20.275000  ...    13.8   0.0   0.0  18.650000  14.966667  19.640000
5      22.850000  ...     0.0   0.0   0.0  16.150000  16.900000  24.100000
6      19.100000  ...     0.0  21.7   0.0  19.100000  18.250000  20.771429
7      19.200000  ...     0.0  18.0   0.0  18.914286  19.350000  20.350000
8      22.257143  ...     0.0   0.0  20.2  20.700000  18.100000  17.800000
9       0.000000  ...     0.0   0.0   0.0   0.000000   0.000000   0.000000

month
day          sun        thu    tue    wed
X
1      22.066667  21.525000  20.70   0.00
2      17.700000   0.000000  17.60  20.05
3      21.380000  17.850000  15.90  18.50
4      20.016667  21.071429  16.50  20.54
5       0.000000  21.600000   0.00  23.90
6      21.766667  17.750000  19.18  25.35
7      18.733333  19.400000  20.70  12.95
8      17.800000  23.450000  18.65   0.00
9       0.000000   0.000000  24.30   0.00

[9 rows x 64 columns]

### 10.2.6. 다중 인덱스
여러 그룹을 데이터 프레임으로 나타내는 것을 다중 인덱스(multi index) 라고 부른다.

예시로 고객의 신상 정보와, 정기예금 가입여부를 모아놓은 데이터를 사용하자

In [100]:
import pandas as pd

In [101]:
bank = pd.read_csv('bank.csv')

In [102]:
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [103]:
# 대표적으로, 피봇 테이블을 만들때 다중 인덱스가 만들어진다.
# 정기예금 가입 여부 별 결혼유무별 직업의 통장 잔고값을 피봇 테이블로 만들어보자.
pivot_df = bank.pivot_table(index=['y', 'marital'], columns='job', values='balance', fill_value=0)
pivot_df

job                admin.  blue-collar  entrepreneur     housemaid  \
y   marital
no  divorced   854.431034   788.956522   1102.538462    405.444444
    married   1357.608511  1038.893617   1636.918699   1758.610390
    single    1106.692913  1451.366667   2738.823529   3309.916667
yes divorced  1628.363636   440.100000    -32.333333   2878.000000
    married   1320.354839  1543.142857   1283.555556   1768.857143
    single    1149.500000   517.375000    897.333333  10237.000000

job            management      retired  self-employed     services  \
y   marital
no  divorced  1313.990654  1622.814815    2921.600000   974.666667
    married   1889.041667  2289.092857    1379.554622  1242.354545
    single    1743.912351  3909.666667     896.882353   877.323810
yes divorced  2487.750000  2022.312500    1873.000000   640.625000
    married   1665.090909  2752.388889     925.375000  1031.000000
    single    1643.571429  1247.500000    2023.714286  1475.714286

job               student   technician   unemployed      unknown
y   marital
no  divorced     0.000000   879.012346   842.909091   137.000000
    married    519.222222  1437.311653  1048.075758  1201.208333
    single    1825.732143  1286.365957  1272.592593  3108.333333
yes divorced     0.000000   509.375000     0.000000     0.000000
    married     10.000000  1433.476190  1744.000000  1574.833333
    single    1264.277778  1638.181818   418.250000     0.000000

In [104]:
# .melt() 를 사용해 다중 인덱스를 풀어보자.
melted_df = pd.melt(pivot_df)

In [105]:
melted_df.iloc[:12]

            job        value
0        admin.   854.431034
1        admin.  1357.608511
2        admin.  1106.692913
3        admin.  1628.363636
4        admin.  1320.354839
5        admin.  1149.500000
6   blue-collar   788.956522
7   blue-collar  1038.893617
8   blue-collar  1451.366667
9   blue-collar   440.100000
10  blue-collar  1543.142857
11  blue-collar   517.375000

## 10.3. merging, joining, concatenating
### 10.3.1. append
존재하는 데이터 프레임에 자료를 추가하는 것을 어팬드(append) 라고 부른다.

예제 데이터로 산불 자료를 사용하자.

In [106]:
import pandas as pd

In [107]:
df = pd.read_excel('forestfires.xlsx')

In [108]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [109]:
# 연습을 위해 임의로 두 데이터 프레임 df1 과 df2 를 만들자.
df1 = df.iloc[:10]  # 첫 열줄
df1.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [110]:
df2 = df.iloc[-10:]  # 마지막 열줄
df2.head()

     X  Y month  day  FFMC    DMC     DC  ISI  temp  RH  wind  rain  area
507  2  4   aug  fri  91.0  166.9  752.6  7.1  25.9  41   3.6   0.0  0.00
508  1  2   aug  fri  91.0  166.9  752.6  7.1  25.9  41   3.6   0.0  0.00
509  5  4   aug  fri  91.0  166.9  752.6  7.1  21.1  71   7.6   1.4  2.17
510  6  5   aug  fri  91.0  166.9  752.6  7.1  18.2  62   5.4   0.0  0.43
511  8  6   aug  sun  81.6   56.7  665.6  1.9  27.8  35   2.7   0.0  0.00

In [111]:
# df1 뒤에 df2 를 붙여보자.
df1.append(df2)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [112]:
# 행 번호를 살펴보면, 9 다음의 숫자가 507 이다. 기존 인덱스를 무시하도록 ignore_index=True 라는 옵션을 넘겨보자.
df1.append(df2, ignore_index=True)

    X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0   7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1   7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3   8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5   8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7   8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9   7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
11  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
12  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
13  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
14  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
15  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
16  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
17  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
18  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
19  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [113]:
# 리스트를 사용해 한번에 여러 데이터 프레임을 어팬드할 수 있다.
df3 = df.iloc[10:20]  # 10에서 20 번째 줄
df1.append([df2, df3])

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00

In [114]:
# 이번에는 df1의 끝에 한 줄만 더 추가해보자.
one_row = df.iloc[-1]    # 마지막 줄
one_row

X            6
Y            3
month      nov
day        tue
FFMC      79.5
DMC          3
DC       106.7
ISI        1.1
temp      11.8
RH          31
wind       4.5
rain         0
area         0
Name: 516, dtype: object

In [115]:
# 데이터 프레임에 시리즈를 어팬드해보자.
df1.append(one_row)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.0

### 10.3.2. concatenate
concatenate 방식으로 두 개 이상의 데이터 프레임을 합쳐보자.

pd.concat([df1, df2])

산불 데이터를 예제로 사용하자.

In [116]:
import pandas as pd

In [117]:
df = pd.read_excel('forestfires.xlsx')

In [118]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [119]:
# 임의로 데이터 프레임을 나눠보자.
xy = df[['X', 'Y']][:5]    # X, Y 열의 첫 5 줄

In [120]:
xy

   X  Y
0  7  5
1  7  4
2  7  4
3  8  6
4  8  6

In [121]:
xy2 = df[['X', 'Y']][-5:]    # X, Y 열의 마지막 5 줄
xy2

     X  Y
512  4  3
513  2  4
514  7  4
515  1  4
516  6  3

In [122]:
# pd.concat()을 사용해 수직으로 xy 와 xy2를 연결시켜보자.
pd.concat([xy, xy2])

     X  Y
0    7  5
1    7  4
2    7  4
3    8  6
4    8  6
512  4  3
513  2  4
514  7  4
515  1  4
516  6  3

In [123]:
# 행이름을 무시하도록 ignore_index=True옵션을 넘겨보자.
pd.concat([xy, xy2], ignore_index=True)

   X  Y
0  7  5
1  7  4
2  7  4
3  8  6
4  8  6
5  4  3
6  2  4
7  7  4
8  1  4
9  6  3

In [124]:
# append 에서는 수평으로 데이터를 합칠 수 없지만, concat 에서는 axis=1 옵션으로 가능하다
wind = df[['wind']][:5]  # 첫 5 줄
wind

   wind
0   6.7
1   0.9
2   1.3
3   4.0
4   1.8

In [125]:
pd.concat([xy, wind]) # xy 와 wind를 수평으로 합쳐보자.

     X    Y  wind
0  7.0  5.0   NaN
1  7.0  4.0   NaN
2  7.0  4.0   NaN
3  8.0  6.0   NaN
4  8.0  6.0   NaN
0  NaN  NaN   6.7
1  NaN  NaN   0.9
2  NaN  NaN   1.3
3  NaN  NaN   4.0
4  NaN  NaN   1.8

In [126]:
# axis=1옵션을 넘겨보자.
pd.concat([xy, wind], axis=1)

   X  Y  wind
0  7  5   6.7
1  7  4   0.9
2  7  4   1.3
3  8  6   4.0
4  8  6   1.8

In [127]:
# X 열이 두 데이터 프레임에서 겹치도록 wind2 를 만들어보자.
wind2 = df[['wind', 'X']][:5]
wind2

   wind  X
0   6.7  7
1   0.9  7
2   1.3  7
3   4.0  8
4   1.8  8

In [128]:
xy # xy의 모양은 다음과 같다.

   X  Y
0  7  5
1  7  4
2  7  4
3  8  6
4  8  6

In [129]:
pd.concat([xy, wind2]) # 이 둘을 concat 으로 합쳐보자.

   X    Y  wind
0  7  5.0   NaN
1  7  4.0   NaN
2  7  4.0   NaN
3  8  6.0   NaN
4  8  6.0   NaN
0  7  NaN   6.7
1  7  NaN   0.9
2  7  NaN   1.3
3  8  NaN   4.0
4  8  NaN   1.8

In [130]:
pd.concat([xy, wind2], join='inner') # 이번에는 join='inner'옵션을 넘겨보자.'inner' 옵션은 데이터 프레임의 교집합만 나타낼것을 의미한다.

   X
0  7
1  7
2  7
3  8
4  8
0  7
1  7
2  7
3  8
4  8

### 10.3.3. replace
데이터 프레임 내에 있는 특정 값을, 원하는 값으로 변경할 수 있다.

값을 변경할 때는 판다스의 .replace() 메써드를 사용한다.

예시로 adult 데이터를 살펴보자.

In [131]:
import pandas as pd

In [132]:
df = pd.read_csv('adult.csv', header=None, skipinitialspace=True)

In [133]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [134]:
# 9번 열의 Male, Female 값을 '남', '여' 값으로 바꿔보자. .replace() 안에, 찾아야할 값과, 바꿀 값을 넘겨주면 된다.
df.replace('Male', '남').head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,남,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,남,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,남,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,남,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [135]:
# 9번 열의 값이 바뀌었다. 이번에는 Female 을 '여'로 값을 바꿔보자.
df.replace('Female', '여').head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,여,0,0,40,Cuba,<=50K

In [136]:
# 만약 이를 df 에 저장하고 싶다면 inplace=True옵션을 넘겨야 한다.
df.replace('Female', '여', inplace=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,여,0,0,40,Cuba,<=50K

In [137]:
# 사전을 이용해 한번에 이를 바꿀 수 있다.
df.replace({'Male': '남', 'Female': '여'}).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,남,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,남,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,남,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,남,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,여,0,0,40,Cuba,<=50K

In [138]:
# 리스트를 사용할수도 있다.
df.replace(['Male', 'Female'], ['남', '여']).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,남,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,남,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,남,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,남,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,여,0,0,40,Cuba,<=50K

In [140]:
# regex=True 옵션을 넘기면 정규표현을 사용해 문자열을 바꿀수도 있다. 문자열에서 간혹 보이는 '-' 표시를 ' ' 표시로 바꿔보자.
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,여,0,0,40,Cuba,<=50K

In [141]:
df.replace(r'-', ' ', regex=True).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State gov,77516,Bachelors,13,Never married,Adm clerical,Not in family,White,Male,2174,0,40,United States,<=50K
1,50,Self emp not inc,83311,Bachelors,13,Married civ spouse,Exec managerial,Husband,White,Male,0,0,13,United States,<=50K
2,38,Private,215646,HS grad,9,Divorced,Handlers cleaners,Not in family,White,Male,0,0,40,United States,<=50K
3,53,Private,234721,11th,7,Married civ spouse,Handlers cleaners,Husband,Black,Male,0,0,40,United States,<=50K
4,28,Private,338409,Bachelors,13,Married civ spouse,Prof specialty,Wife,Black,여,0,0,40,Cuba,<=50K