# 8. pandas
## 8.1 판다스로 파일 다루기
### 8.1.1. 파일 불러오기
다양한 형태의 자료를 판다스로 불러오고 내보내보자.

In [1]:
import pandas as pd

#### csv
csv 파일은 Comma-Separated Values 를 의미한다. 즉, (, ;, \t) 등으로 구분이 되어있는 자료를 의미한다.

csv 자료를 불러올때는 .read_csv 를 사용한다.

In [3]:
bank = pd.read_csv('bank.csv')  # bank 로 저장

In [4]:
bank.head() # 자료가 불려왔는지 확인해보자.

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

#### header
http://archive.ics.uci.edu/ml/datasets/Adult 에서 데이터를 다운 받는다. 이번 파일은 사람들의 성별, 나이, 노동시간 등의 정보를 담고 있다

In [9]:
adult = pd.read_csv('adult.csv')
adult.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [10]:
# 이 자료의 특징으로는, 열의 이름이 없어, 첫 행이 열의 이름으로 불려왔다는 점이다.
# 이런 상황을 예방하고 싶다면, header 라는 옵션을 None으로 지정하면 된다.
adult = pd.read_csv('adult.csv', header=None)
adult.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

#### excel
이번에는 엑셀 파일을 불러와보자. http://archive.ics.uci.edu/ml/datasets/Forest+Fires 에서 데이터를 다운받아 엑셀 파일로 먼저 변환을 한다. 엑셀파일은 .read_excel로 불러올 수 있다.

In [12]:
forest = pd.read_excel('forestfires.xlsx')
forest.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

### 8.1.2. 파일로 저장하기
#### to_csv
.to_csv로 데이터 프레임을 파일로 저장할 수 있다.

In [13]:
forest.to_csv('forest.csv')

In [14]:
# 해당 파일이 저장되었는지 확인해보자.
import os
os.path.exists('forest.csv')    # 파일이 존재하는지 확인

True

#### header & index
이번에는 adult를 csv 로 저장해보자.

In [16]:
adult.to_csv('adult2.csv')
# 파일을 확인해보니, 행 이름은 전에 연습삼아 지정해놓은 대로 저장되었으며, 열 이름은 숫자로 되어있다.

In [17]:
# header옵션과 index 를 지정하면, 이를 해결할 수 있다.
adult.to_csv('adult2.csv', header=0, index=0)
# 다시 확인해보니, 이번에는 행과 열 이름이 사라졌다.

## 8.2 데이터 프레임 다루기
데이터 프레임을 다루는 구체적인 방법을 살펴보자.

### 8.2.1. csv 데이터 불러오기
예제 데이터를 불러와보자.

예제 데이터는 포르투갈에서 발생한 산불과 관련된 데이터이다.

In [18]:
df = pd.read_csv('forest.csv')

In [19]:
df.head()

,Unnamed: 0,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
0,0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
1,1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
2,2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
3,3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
4,4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

### 8.2.2. 열 접근
데이터 프레임에서 원하는 값을 다양한 방법으로 선택할 수 있다.

[] 안에 열의 이름을 넣으면 열만 선택할 수 있다.

In [20]:
df['month'].head()

0    mar
1    oct
2    oct
3    mar
4    mar
Name: month, dtype: object

In [21]:
# 하나의 열은 Series 형태로 나온다. 여기에서 Series 에서 작동하듯, indexing/slicing 을 통해 자료에 접근할 수 있다.
df['month'][0]    # 열의 첫번째 값

'mar'

In [22]:
df['month'][:5]  # 첫 다섯개 값

0    mar
1    oct
2    oct
3    mar
4    mar
Name: month, dtype: object

#### 하위 데이터 프레임
[[]] 를 사용해 하위 데이터 프레임을 만들 수 있다.

In [23]:
df[['month', 'day', 'rain']].head()

  month  day  rain
0   mar  fri   0.0
1   oct  tue   0.0
2   oct  sat   0.0
3   mar  fri   0.2
4   mar  sun   0.0

In [24]:
# month, day, rain 의 열을 갖는 첫 10 행만 담는 데이터 프레임을 만들어보자.
df[['month', 'day', 'rain']][:10]

  month  day  rain
0   mar  fri   0.0
1   oct  tue   0.0
2   oct  sat   0.0
3   mar  fri   0.2
4   mar  sun   0.0
5   aug  sun   0.0
6   aug  mon   0.0
7   aug  mon   0.0
8   sep  tue   0.0
9   sep  sat   0.0

### 8.2.3 행 접근
행에 접근할때는 .loc 이나 .iloc 을 사용한다. .loc 은 행의 이름으로 정보를 찾을때 사용한다. .iloc 은 행의 index 번호로 자료를 찾을 때 사용한다.

In [25]:
df.loc[0]    # 행 이름이 0 인 자료 정보

Unnamed: 0       0
X                7
Y                5
month          mar
day            fri
FFMC          86.2
DMC           26.2
DC            94.3
ISI            5.1
temp           8.2
RH              51
wind           6.7
rain             0
area             0
Name: 0, dtype: object

In [26]:
df.iloc[0]  # 첫 행 정보

Unnamed: 0       0
X                7
Y                5
month          mar
day            fri
FFMC          86.2
DMC           26.2
DC            94.3
ISI            5.1
temp           8.2
RH              51
wind           6.7
rain             0
area             0
Name: 0, dtype: object

In [27]:
# 뒤에 열 이름으로 색인해주면 한 자료에 접근할 수 있다.
df.iloc[0]['temp']

8.2

In [28]:
# 이를 다르게 표현할 수 있다.
df.loc[0, 'temp']

8.2

In [29]:
# slicing 을 사용해 여러 값을 선택할 수 있다.
df.iloc[:3]['temp']

0     8.2
1    18.0
2    14.6
Name: temp, dtype: float64

#### 하위 데이터 프레임
.iloc에서 indexing 을 사용해 하위 데이터 프레임을 만들 수 있다.

In [30]:
df.iloc[:5]  # 첫 다섯개 행으로 하위 데이터 프레임 만들기

,Unnamed: 0,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
0,0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
1,1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
2,2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
3,3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
4,4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

In [31]:
df.loc[[0, 3, 5]]    # 0, 3, 5 라는 이름을 가진 행을 가진 데이터 프레임

,Unnamed: 0,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
0,0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
3,3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
5,5,8,6,aug,sun,92.3,85.3,488.0,14.7,22.2,29,5.4,0.0,0.0

In [32]:
# 하나의 값에 접근할 때, .at를 사용하기도 한다.
df.at[0, 'month']    # 행의 이름이 0 이며 열의 이름이 month 인 정보

'mar'

### 8.2.4 set index
현재 행의 이름(index)는 숫자로 되어있다. 숫자가 아닌 열의 정보로 행의 이름을 지정하고 싶다면, .set_index() 를 사용한다.
현재 index 는 .index 로 확인할 수 있다.

In [33]:
df.index    # 0-517 까지의 숫자

RangeIndex(start=0, stop=517, step=1)

In [34]:
# X 값을 index 로 지정해보자.
df.set_index('X').head()

,Unnamed: 0,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
X,,,,,,,,,,,,,
7,0,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
7,1,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
7,2,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
8,3,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
8,4,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

In [36]:
df2 = df.set_index('X') # index 가 지정되었다. 이를 df2에 저장하자.
df2.head()  # 확인

,Unnamed: 0,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
X,,,,,,,,,,,,,
7,0,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
7,1,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
7,2,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
8,3,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
8,4,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

### 8.2.5. inplace
df를 확인해보면, .set_index가 적용되지 않았다.

In [37]:
df.head()

,Unnamed: 0,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
0,0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
1,1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
2,2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
3,3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
4,4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

pandas의 많은 메써드는 원본 데이터 프레임에 변화를 자동으로 저장하지 않는다. 만약 같은 변수의 이름의 데이터 프레임에 가공을 하고 싶다면, inplace=True 옵션을 넘겨 항상 새로운 변수에 저장하지 않아도 되는 번거로움을 없앨 수 있다.

In [38]:
df.set_index('X', inplace=True)
df.head()

,Unnamed: 0,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
X,,,,,,,,,,,,,
7,0,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0
7,1,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
7,2,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
8,3,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
8,4,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0

In [39]:
# 편의를 위해 df 를 원래대로 돌려놓자
df = pd.read_csv('forest.csv')

### 8.2.6. reindex
열 혹은 행의 순서를 바꾸고 싶을때 .reindex 를 사용한다.

In [40]:
# 열 순서 바꾸기
# df 의 컬럼을 month, day, X, Y 로 바꿔보자.
df.reindex(columns=['month', 'day', 'X', 'Y']).head()

  month  day  X  Y
0   mar  fri  7  5
1   oct  tue  7  4
2   oct  sat  7  4
3   mar  fri  8  6
4   mar  sun  8  6

In [41]:
# index 순서 바꾸기
# 행의 순서도 바꿀 수 있다. 행의 이름을 기준으로, 순서가 4, 3, 2, 1, 0 이 되도록 바꿔보자.
df.reindex(index=[4, 3, 2, 1, 0])

,Unnamed: 0,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
4,4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0
3,3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0
2,2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0
1,1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0
0,0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0

## 8.3 sorting
데이터 프레임 정렬에 대해 배워보자.

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('adult.csv', header=None)

In [44]:
# 이 자료는 header 가 없기 때문에, 따로 열 이름을 지정해줘야 한다. 자세한 사항은 rename 강의에 나와있다.
titles = {0: '나이', 1: '고용형태', 2: '가중치',
            3: '최종학위', 4:'교육햇수', 5: '결혼유무',
            6: '직업명', 7:'가족내역할', 8:'인종',
            9: '성별', 10: '자본이득', 11: '자본손실',
            12: '노동시간', 13:'고향', 14:'수입'
         }

In [45]:
df.rename(columns=titles, inplace=True)

In [46]:
df.head()

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

### 8.3.1. 기본 정렬
일단, 나이 순으로 자료를 정렬해보자. 정렬은 .sort_values() 를 이용한다.

In [47]:
df.sort_values('나이').head() 
# 나이가 적은 순으로 정렬되었다.

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
12318,17,Private,127366,11th,7,Never-married,Sales,Own-child,White,Female,0,0,8,United-States,<=50K
6312,17,Private,132755,11th,7,Never-married,Sales,Own-child,White,Male,0,0,15,United-States,<=50K
30927,17,Private,108470,11th,7,Never-married,Other-service,Own-child,Black,Male,0,0,17,United-States,<=50K
12787,17,Local-gov,308901,11th,7,Never-married,Adm-clerical,Own-child,White,Female,0,0,15,United-States,<=50K
25755,17,?,47407,11th,7,Never-married,?,Own-child,White,Male,0,0,10,United-States,<=50K

### 8.3.2. 내림차순 정렬
정렬 순서를 바꾸고 싶다면 ascending=False 옵션을 지정해주면 된다. ascending 의 초기값은 True로 오름차순이 기본 설정이다.

In [49]:
df.sort_values('나이', ascending=False).head()
# 나이가 많은 순으로 정렬 되었다.

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
5406,90,Private,51744,Masters,14,Never-married,Exec-managerial,Not-in-family,Black,Male,0,0,50,United-States,>50K
6624,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
20610,90,Private,206667,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
1040,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
1935,90,Private,221832,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,<=50K

### 8.3.3. 다중 정렬
한번에 여러 열을 정렬할 수 있다.

0번 열의 나이는 내림차순, 4번 열의 교육 햇수는 오름차순으로 정렬해보자.

In [51]:
df.sort_values(['나이', '교육햇수'], ascending=[False, True]).head()
# 나이는 많지만 교육 햇수는 적은 순으로 정렬되었다.

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,직업명,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
24238,90,?,166343,1st-4th,2,Widowed,?,Not-in-family,Black,Female,0,0,40,United-States,<=50K
19747,90,Private,226968,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
25303,90,?,175444,7th-8th,4,Separated,?,Not-in-family,White,Female,0,0,15,United-States,<=50K
32367,90,Local-gov,214594,7th-8th,4,Married-civ-spouse,Protective-serv,Husband,White,Male,2653,0,40,United-States,<=50K
5272,90,Private,141758,9th,5,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K

### 8.3.4. index 정렬
위에서는 값을 기준으로 정렬시켰지만, 이번에는 행의 이름을 기준으로 정렬을 해보자.

먼저 6번 직업명의 열을 행이름으로 설정하자.

In [52]:
df.set_index('직업명').head()

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
직업명,,,,,,,,,,,,,,
Adm-clerical,39,State-gov,77516,Bachelors,13,Never-married,Not-in-family,White,Male,2174,0,40,United-States,<=50K
Exec-managerial,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,White,Male,0,0,13,United-States,<=50K
Handlers-cleaners,38,Private,215646,HS-grad,9,Divorced,Not-in-family,White,Male,0,0,40,United-States,<=50K
Handlers-cleaners,53,Private,234721,11th,7,Married-civ-spouse,Husband,Black,Male,0,0,40,United-States,<=50K
Prof-specialty,28,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Black,Female,0,0,40,Cuba,<=50K

In [53]:
df2 = df.set_index('직업명') # 이를 df2라고 저장하자.

In [55]:
df2.sort_index().head() # 행 이름을 기준으로 정렬해보자. 행 이름을 기준으로 정렬은 .sort_index()를 사용한다.
# 직업명 기준으로 정렬되었다.

,나이,고용형태,가중치,최종학위,교육햇수,결혼유무,가족내역할,인종,성별,자본이득,자본손실,노동시간,고향,수입
직업명,,,,,,,,,,,,,,
?,60,?,56248,HS-grad,9,Married-civ-spouse,Husband,White,Male,0,1485,70,United-States,>50K
?,49,?,350759,HS-grad,9,Married-civ-spouse,Husband,White,Male,0,0,40,United-States,<=50K
?,22,?,117618,Bachelors,13,Never-married,Not-in-family,White,Male,0,0,25,United-States,<=50K
?,54,?,148657,Preschool,1,Married-civ-spouse,Wife,White,Female,0,0,40,Mexico,<=50K
?,67,?,81761,HS-grad,9,Divorced,Own-child,White,Male,0,0,20,United-States,<=50K

## 8.4 Filtering
데이터 프레임에서 원하는 조건의 값만 필터링 해보자.

예제 데이터는 고객의 은행 신상 정보다.

In [57]:
import pandas as pd
bank = pd.read_csv('bank.csv')
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [58]:
bank.shape # 자료는 4,521개의 행과 17개의 열로 이루어진다.

(4521, 17)

### 8.4.1. 비교
비교연산자를 사용해 일정 조건에 충족하는 값만 추출해보자.

나이가 35세 이전인 값만 추출해보자.

In [59]:
under_35 = bank['age'] < 35 # under_35 변수에 이를 저장해보겠다
under_35.head()
# Series 안에 불리안 형태로 결과가 출력된다.

0     True
1     True
2    False
3     True
4    False
Name: age, dtype: bool

In [60]:
young = bank[under_35]
young.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
13,20,student,single,secondary,no,502,no,no,cellular,30,apr,261,1,-1,0,unknown,yes
14,31,blue-collar,married,secondary,no,360,yes,yes,cellular,29,jan,89,1,241,1,failure,no

In [61]:
young.shape # young의 shape를 확인해보니, 행의 갯수가 1,472개로 줄었다.

(1472, 17)

In [62]:
# young은 나이가 35세 이전인 사람들의 자료만 모아놓은 데이터 프레임이다.
#이를 한번에 표현하면 다음과 같다.
young = bank[bank['age'] < 35]
young.shape

(1472, 17)

In [63]:
# 이번에는 marital 이 'married' 인 사람들만 추출해보자.
married = bank[bank['marital'] == 'married']
married.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no

In [64]:
married.shape # 필터링으로 인해 행의 수가 줄어든것을 볼 수 있다. 이제는 결혼한 사람들만 선택되었다.

(2797, 17)

In [65]:
# 이번에는 두가지 조건을 모두 만족하는 값을 추출해보자. 두 조건이 모두 충족하는 값을 찾을때는 &를 사용한다.
# 이를 young_married에 저장해보자.
young_married = bank[(bank['marital'] == 'married') & (bank['age'] < 35)]
young_married.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
14,31,blue-collar,married,secondary,no,360,yes,yes,cellular,29,jan,89,1,241,1,failure,no
19,31,services,married,secondary,no,132,no,no,cellular,7,jul,148,1,152,1,other,no

In [66]:
young_married.shape

(639, 17)

In [68]:
# 이번에는 두가지 조건 중 하나만 충족하는 값을 추출해보자. 두 조건 중 하나만 충족하는 값을 찾을때는 | 를 사용한다.
young_married = bank[(bank['marital'] == 'married') | (bank['age'] < 35)]
young_married.head()
# 35세 이하이거나 결혼한 사람들이 선택되었다.

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no

## 8.5. 간단한 열 정보 얻기
pandas 에서 손쉽게 열에 대해 통계 정보를 얻을 수 있다.

예제는 포르투갈에서 발생한 산불에 대한 정보이다.

In [69]:
import pandas as pd
df = pd.read_excel('forestfires.xlsx')
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

### 8.5.1. 통계

In [70]:
df['rain'].mean()

0.02166344294003869

In [71]:
# .sum()으로 총 면적을 구해보자.
df['area'].sum()

6642.049999999999

In [72]:
# median으로 X 좌표의 중앙값을 구해보자.
df['X'].median()

4.0

In [73]:
# .mode()으로 Y 좌표의 최빈값을 구해보자.
df['Y'].mode()

0    4
dtype: int64

In [74]:
# standard deviation: .std()로 습도의 표준편차를 구해보자.
df['RH'].std()

16.317469239378394

### 8.5.2. 색인

In [75]:
# min 온도의 최소값을 구해보자.
df['temp'].min()

2.2

In [76]:
# max 온도의 최고값을 구해보자.
df['temp'].max()

33.3

In [77]:
# idxmin 최저 온도의 행 위치를 보고 싶을때는 .idxmin()을 사용한다.
df['temp'].idxmin()
# 280 번째 행에 최저값이 위치해있다.

280

In [78]:
# idxmax 최고 온도의 행 위치를 보자.
df['temp'].idxmax()

498

### 8.5.3. 요약 정보

In [79]:
# .unique() 는 등장한 값의 종류를 보여준다.
# 어떤 요일에 산불이 났는지 확인해보자.
df['day'].unique()

array(['fri', 'tue', 'sat', 'sun', 'mon', 'wed', 'thu'], dtype=object)

In [81]:
# .nunique()함수는 몇개의 값의 종류가 있는지 보여준다.
# 요일에 대한 값의 종류가 몇개인지 구해보자.
df['day'].nunique()
# 산불이 발생한 요일은 총 7개임을 알 수 있다.

7

In [82]:
# value_counts()로 각 값의 출현 빈도를 구할 수 있다.
# 어느 달에 산불이 가장 많이 발생했는지 확인해보자.
df['month'].value_counts()
# 확인결과, 8월과 9월에 산불이 가장 많이 발생했다.

aug    184
sep    172
mar     54
jul     32
feb     20
jun     17
oct     15
dec      9
apr      9
jan      2
may      2
nov      1
Name: month, dtype: int64